<?php 
return array( 
'default_pwd'=>'111111',
'thum_width'=>'120',
'thum_height'=>'80',
'upload_size'=>'2',
'upload_type'=>'jpg|gif|png',
'watermark'=>'1',
'mark_type'=>'0',
'font'=>'',
'font_color'=>'',
'font_size'=>'',
'mark_pic'=>'data/app/1377759370.jpg',
'mark_place'=>'9',
'mail_type'=>'',
'mail_host'=>'',
'mail_post'=>'',
'mail_mail'=>'',
'mail_user'=>'',
'mail_pwd'=>'',
'province_vip1_market_present'=>'',//省代市场比例
'province_vip2_market_present'=>'',
'province_vip1_market_quotiety'=>'',//省代市场系数
'province_vip2_market_quotiety'=>'',
'direct_vip1_market_present'=>'',//直营市场比例
'direct_vip2_market_present'=>'',
'direct_vip1_market_quotiety'=>'',//省代市场系数
'direct_vip2_market_quotiety'=>'',
'activity_credits'=>'',//自定义活动积分
'activity_total_price'=>'',//自定义活动订货额
'activity_sales'=>'',//自定义活动销售额
'helpsell_credits'=>'',//自定义助销工具积分
'helpsell_total_price'=>'',//自定义助销工具积分
'agency_province_market_present'=>'',//省代市场代理商市场比例
'agency_province_market_quotiety'=>'',//省代市场代理商市场系数
'agency_direct_market_present'=>'',//直营市场代理商市场比例
'agency_direct_market_quotiety'=>'',//直营市场代理商市场系数
); 
 ?>